#!/usr/bin/env python -W ignore::DeprecationWarning

from lib.pandora import Pandora,__version__
from optparse import OptionParser
import sys


def main():

   usage = """usage: %prog [options] command

Commands:
  play                 Play music, if not already playing
  pause                Pause music, if not already paused
  play_pause           Toggle play/pause state
  skip                 Skip to the next song
  is_playing           Test whether the music is currently playing
  is_paused            Test whether the music is currently paused"""

   parser = OptionParser(usage=usage, version=".".join(map(str,__version__)))
   parser.add_option("-H", "--host", type="string", default="localhost",
                     help="default: localhost")
   parser.add_option("-p", "--port", type="int", default=9222,
                     help="default: 9222")
   (options, args) = parser.parse_args()

   if len(args) < 1:
      parser.error("Must specify cmd")
   elif len(args) > 1:
      parser.error("Only one command is allowed")
   cmd = args[0]

   with Pandora() as p:
      if cmd == "play":
         p.play()
      elif cmd == "pause":
         p.pause()
      elif cmd == "toggle":
         p.play_pause()
      elif cmd == "skip":
         p.skip()
      elif cmd == "is_playing":
         print p.is_playing()
      elif cmd == "is_paused":
         print p.is_paused()
      else:
         print "Unknown cmd '%s'" % cmd
         exit(1)


if __name__ == "__main__":
   main()
